version: 0.2

phases:
  install:
    commands:
      - sudo update-ca-certificates -f
  pre_build:
    commands:
      - echo Running maven clean
      - mvn -X -f mymarkall/pom.xml clean
  build:
    commands:
      - echo Build started on `date`
      - mvn -X -f mymarkapi/pom.xml install
      - mvn -X -f mymarkapp/pom.xml install
      
