version: 0.2

environment_variables:
  plaintext:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - sudo update-ca-certificates -f
  pre_build:
    commands:
      - echo Running maven clean
      - mvn -X -f mymarkall/pom.xml clean
  build:
    commands:
      - echo Build started on `date`
      - echo Building mymarkapi
      - mvn -f mymarkapi/pom.xml install
      - echo Building mymarkapp
      - mvn -f mymarkapp/pom.xml install
      - echo Building mymarkservice
      - mvn -f mymarkservice/pom.xml install
      
