-- INSERT INTO greeting (simple_message, named_message, language) values ("Hello World!","Hello {name}!", "ENG");
-- INSERT INTO greeting (simple_message, named_message, language) values ("Hello World in Spanish!","Hello {name} in Spanish!", "SPA");
-- INSERT INTO greeting (simple_message, named_message, language) values ("Hello World in French!","Hello {name} in French!", "FRA");
-- 

INSERT INTO country (code, name) values ("CA", "Canada");
INSERT INTO country (code, name) values ("US", "United States");
INSERT INTO country (code, name) values ("UK", "United Kingdom");

INSERT INTO state (name, code, country_id) values ("Alabama","AL", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Alaska","AK", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Arizona","AZ", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Arkansas","AR", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("California","CA", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Colorado","CO", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Connecticut","CT", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Delaware","DE", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("District of Columbia","DC", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Florida","FL", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Georgia","GA", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Hawaii","HI", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Idaho","ID", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Illinois","IL", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Indiana","IN", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Iowa","IA", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Kansas","KS", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Kentucky","KY", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Louisiana","LA", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Maine","ME", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Maryland","MD", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Massachusetts","MA", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Michigan","MI", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Minnesota","MN", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Mississippi","MS", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Missouri","MO", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Montana","MT", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Nebraska","NE", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Nevada","NV", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("New Hampshire","NH", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("New Jersey","NJ", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("New Mexico","NM", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("New York","NY", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("North Carolina","NC", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("North Dakota","ND", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Ohio","OH", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Oklahoma","OK", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Oregon","OR", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Pennsylvania","PA", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Rhode Island","RI", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("South Carolina","SC", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("South Dakota","SD", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Tennessee","TN", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Texas","TX", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Utah","UT", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Vermont","VT", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Virginia","VA", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Washington","WA", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("West Virginia","WV", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Wisconsin","WI", (SELECT c.id from country c where c.code="US"));
INSERT INTO state (name, code, country_id) values ("Wyoming","WY", (SELECT c.id from country c where c.code="US"));

