
-- Domain Tables
-- DROP TABLE GREETING;

CREATE TABLE `GREETING` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `LANGUAGE` varchar(10) NOT NULL,
  `SIMPLE_MESSAGE` varchar(256) DEFAULT NULL,
  `NAMED_MESSAGE` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`ID`)
  ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

